import { TranslationType } from "./zh-TW";

export const fr_FR: TranslationType = {
  common: {
    appName: "TaskRails",
    version: "v2.0",
    importMd: "Importer MD",
    exportMd: "Exporter MD",
    deleteAll: "Tout supprimer",
    deleteAllConfirm: "Êtes-vous sûr de vouloir supprimer toutes les tâches ? Cette action est irréversible.",
    deleteConfirm: "Êtes-vous sûr de vouloir supprimer cette tâche ?",
    importConfirm: "{count} tâches trouvées. Voulez-vous remplacer la liste actuelle ?",
    noTasksFound: "Aucune tâche valide trouvée dans le fichier, veuillez vérifier le format.",
    parseError: "Échec de l'analyse du fichier Markdown.",
    yes: "Oui",
    no: "Non"
  },
  mdExport: {
    header: "TaskRails Project Context",
    autoGenerated: "Ce fichier a été généré automatiquement par TaskRails.",
    roleRegistry: "ROLE REGISTRY",
    missionBoard: "MISSION BOARD",
    status: {
      todo: "À FAIRE",
      doing: "EN COURS",
      done: "TERMINÉ"
    }
  },
  mdImport: {
    statusMap: {
      todo: "À FAIRE",
      doing: "EN COURS",
      done: "TERMINÉ"
    }
  },
  projectConfig: {
    items: {
      projectName: "Nom du Projet",
      projectGoal: "Objectif du Projet",
      techStack: "Stack Technique",
      features: "Fonctionnalités",
      dataStructure: "Structure de Données",
      designSpec: "Spécification de Design",
      engineeringRules: "Règles d'Ingénierie",
      team: "Équipe (PM + Architecte)",
      diagrams: "Flux de travail (4 Diagrammes)"
    },
    status: {
      defined: "Défini",
      notSet: "Non défini",
      notGathered: "Non rassemblé",
      notGenerated: "Non généré",
      featuresCount: "{count} fonctionnalités",
      expertsCount: "{count} experts",
      diagramsCount: "{count} diagrammes",
      missing: "Manquant"
    },
    roles: {
      pm: "PM",
      architect: "Architecte",
      expert: "Expert",
      newMember: "Nouveau Membre"
    },
    diagrams: {
      architecture: "Architecture",
      pert: "PERT",
      sequence: "Séquence",
      gantt: "Gantt"
    },
    promptPrefix: "Vous êtes"
  },
  app: {
    kanbanTitle: "Tableau Kanban",
    kanbanSubtitle: "Gestion des tâches et suivi de l'avancement",
    toast: {
      allTasksDeleted: "Toutes les tâches supprimées",
      deleteFailed: "Échec de la suppression",
      aiAnalyzing: "L'IA analyse les spécifications et convoque les agents...",
      aiInjectSuccess: "{rolesCount} agents convoqués et {tasksCount} tâches générées",
      aiInjectFailed: "Échec de l'injection des tâches IA"
    }
  },
  sidebar: {
    all: "Toutes les tâches",
    main: "PRINCIPAL",
    roleSettings: "RÔLES",
    kanban: "BRIDGE KANBAN",
    missions: "MISSIONS",
    engineering: "INGÉNIERIE",
    issues: "PROBLÈMES",
    commits: "COMMITS",
    history: "HISTORIQUE",
    specs: "SPÉCIFICATIONS",
    manual: "Manuel",
    admin: "ADMIN",
    system_op: "SYSTEM_OP"
  },
  projectAnalyzerUI: {
    title: "Analyseur de Projet",
    subtitle: "Scanner le Code → Analyse IA → Générer Automatiquement les Spécifications",
    loading: {
      scanning: "Scan de la structure du projet",
      scanningFiles: "Analyse des fichiers et de la pile technologique...",
      aiAnalyzing: "Analyse IA en cours",
      lmStudio: "Génération avec LM Studio...",
      ollama: "Génération avec Ollama...",
      cloud: "Génération avec l'IA Cloud..."
    },
    aiSource: { lmStudio: "LM Studio", ollama: "Ollama", cloud: "IA Cloud" },
    buttons: {
      projectScan: "Scanner le Projet", scanning: "Scan en cours...", startScan: "Démarrer le Scan",
      aiGenerate: "IA Générer les Spécifications", generating: "Génération...", generate: "IA Générer",
      saveToMemory: "Enregistrer en Mémoire", saveToSpec: "Enregistrer dans les Spécifications",
      distributeAgents: "Distribuer les Agents", distributeDiagrams: "Distribuer les Diagrammes", distributeAll: "Tout Distribuer"
    },
    labels: { fileCount: "Fichiers", linesOfCode: "Lignes de Code", techStack: "Pile Technologique", entryPoint: "Point d'Entrée", keyFiles: "Fichiers Clés (Top 10)" },
    placeholders: { clickScan: "Cliquez sur 'Démarrer le Scan' pour analyser la structure du projet", scanFirst: "Scannez d'abord le projet, puis cliquez sur 'IA Générer'", aiWillGenerate: "L'IA générera automatiquement les spécifications du projet en fonction des résultats du scan" },
    alerts: {
      savedToMemory: "Enregistré dans la banque de mémoire @specs.md",
      savedToSpec: "✅ Enregistré dans les Spécifications du Projet",
      noAgents: "⚠️ Aucun Agent IA généré. Veuillez d'abord exécuter 'IA Générer'",
      agentsDistributed: "✅ {count} Agents IA distribués aux Paramètres d'Équipe",
      noDiagrams: "⚠️ Aucun diagramme généré. Veuillez d'abord exécuter 'IA Générer'",
      diagramsDistributed: "✅ {count} diagrammes distribués au Visualiseur de Flux de Travail",
      notAnalyzed: "⚠️ Analyse IA non terminée. Veuillez d'abord exécuter 'IA Générer'",
      allDistributed: "🎉 Tous les éléments distribués !"
    }
  },
  specs: {
    title: "Spécifications de Conception",
    subtitle: "// Centre de Définition des Besoins et Spécifications //",
    generateAi: "Générer les Specs via l'IA",
    injectTasks: "Déployer sur Kanban",
    selectCategory: "Sélectionner la Catégorie",
    categories: {
        web: "Application Web",
        desktop: "Logiciel de Bureau",
        esp: "Matériel/Firmware (ESP32)",
        backend: "Système Backend/API",
        mobile: "Application Mobile",
        game: "Développement de Jeux",
        web3: "Blockchain/Web3",
        bot: "Bot/Automatisation",
        ml: "Machine Learning/Données",
        extension: "Extension de Navigateur"
    },
    aiChat: {
        title: "Consultant IA en Spécifications",
        placeholder: "Décrivez le logiciel ou les fonctions que vous voulez développer...",
        startConsulting: "Lancer le Conseil Technique",
        stopConsulting: "Arrêter le Conseil",
        applySpec: "Appliquer le Consensus aux Specs",
        aiThinking: "L'IA conçoit l'architecture...",
        welcome: "Bonjour ! Je suis votre architecte technique. Dites-moi ce que vous souhaitez développer, et je vous aiderai à affiner les spécifications via des questions.",
        copy: "Copier",
        stop: "Arrêter",
        systemPrompt: "Prompt Système",
        savePrompt: "Sauvegarder le Prompt",
        copySuccess: "Copié dans le presse-papiers",
        defaultSystemPrompt: `Vous êtes un architecte système senior et un responsable technique. Votre tâche est d'aider l'utilisateur à planifier une "Spécification technique de projet" complète à partir de zéro.
1. Guidage approfondi : Guidez l'utilisateur à réfléchir aux niveaux d'architecture, à la sélection de la pile technique, au schéma de la base de données et aux phases détaillées du développement fonctionnel.
2. Norme linguistique : Utilisez toujours le "Français" pour la communication.
3. Norme de sortie : Lorsque la planification est mûre, suggérez activement ou produisez directement le format JSON suivant :
   \`\`\`json
   { 
     "name": "Nom du projet", 
     "overview": "Vision et aperçu", 
     "techStack": "Liste détaillée de la pile technique", 
     "dataStructure": "Définition de la structure des données", 
     "features": "## Phase 1...\\n## Phase 2...", 
     "design": "Esthétique de conception et normes d'interface utilisateur", 
     "rules": "Principes et normes d'ingénierie" 
   }
   \`\`\``
    },
    placeholders: {
        name: "Nom du Projet",
        overview: "Résumé et objectifs...",
        techStack: "Stack Tech (Frontend, Backend, DB...)",
        dataStructure: "Définition de la Structure de Données...",
        features: "Liste des Fonctions (Triée par Phase 1/2)...",
        design: "Specs de Design (Couleur, Mise en page...)",
        rules: "Règles de Documentation..."
    },
    toast: {
        generated: "Spec IA Générée",
        injected: "{count} tâches importées avec succès",
        apiKeyRequired: "Veuillez d'abord configurer la clé API IA dans les paramètres"
    }
  },
  roleSettings: {
    title: "Paramètres des Rôles",
    subtitle: "Gérer les Agents IA et les Rôles de Collaborateurs",
    defaultRoles: "Rôles par Défaut",
    customRoles: "Rôles Personnalisés",
    addRole: "Ajouter un Rôle",
    roleName: "Nom du Rôle",
    agentName: "Nom de l'Agent",
    roleType: "Type",
    typeAI: "Agent IA",
    typeHuman: "Collaborateur",
    save: "Sauvegarder",
    delete: "Supprimer",
    noCustomRoles: "Aucun rôle personnalisé ajouté",
    default: "Défaut",
    placeholders: { roleName: "ex. Ingénieur Test", agentName: "ex. TestBot-1", systemPrompt: "ex. Vous êtes un ingénieur..." },
    systemPromptLabel: "System Prompt",
    systemPromptDesc: "Envoyé à AI IDE via MCP",
    aiSuggest: "Suggestion IA",
    buttons: { addToQueue: "Ajouter à la File", dispatchToIde: "Envoyer à AI IDE" },
    alerts: { dispatched: "Tâches de {agentName} envoyées à AI IDE!", dispatchFailed: "Erreur: {error}", noTasks: "Pas de tâches", addedToQueue: "{count} tâches ajoutées" },
    defaultAgents: { architect: { name: "Architecte", prompt: "Architecte système" }, developer: { name: "Développeur", prompt: "Développeur senior" }, reviewer: { name: "Réviseur", prompt: "Expert en revue de code" } },
    stats: { goals: "Objectifs", tasks: "Tâches" }
  },
  roles: {
    coder: "Développeur",
    reviewer: "Réviseur",
    architect: "Architecte",
    all: "Tout le Personnel"
  },
  tags: {
    general: "Général",
    feature: "Fonction",
    bug: "Bug",
    enhancement: "Amélioration",
    documentation: "Docs",
    design: "Design"
  },
  kanban: {
    title: "Tableau de Bord",
    subtitle: "// État du Système : NORMAL //",
    searchPlaceholder: "Rechercher des tâches...",
    newTask: "Nouvelle Tâche",
    columns: {
        todo: "À faire",
        doing: "En cours",
        done: "Terminé"
    },
    taskModal: {
        titlePlaceholder: "Titre de la tâche...",
        descPlaceholder: "Description en Markdown...",
        phase: "Phase",
        priority: "Priorité",
        tag: "Tag",
        created: "Date de création",
        assignee: "Assigné à",
        unassigned: "Non assigné",
        delete: "Supprimer",
        cancel: "Annuler",
        save: "Enregistrer",
        rework: "Retravailler",
        reworkDesc: "Copier le contenu vers 'À faire'",
        completed: "Terminé",
        reworked: "Retravaillé",
        enterNumber: "Entrer un nombre",
        sortOrder: "Ordre (Bas=Haute Priorité)"
    }
  },
  missions: {
    title: "Liste des Missions",
    subtitle: "// Aperçu Global des Tâches //",
    stats: {
      todo: "À faire",
      doing: "En cours",
      done: "Terminé",
      reworked: "Retravaillé"
    },
    search: "Recherche par ID, titre ou description...",
    taskCount: "tâches",
    noTasks: "Aucune tâche pour le moment",
    noMatch: "Aucune correspondance trouvée"
  },
  engineering: {
    title: "Zone d'Ingénierie",
    ideControl: "Centre de Contrôle des Commandes IA IDE",
    debug: "EXÉCUTER DEBUG",
    build: "EXÉCUTER BUILD",
    runApp: "LANCER L'APP",
    commandSent: "Commande envoyée à l'IA IDE :",
    noIssues: "Il n'y a actuellement aucune tâche marquée comme BUG.",
    noHistory: "Aucun historique d'opérations pour le moment",
    commitsDeveloping: "L'intégration de l'historique des commits Git est en cours de développement...",
    proposal: {
        issues: "Suivi des Problèmes : Intègre le système de tâches aux rapports de bugs, liant les changements de code aux IDs de problèmes.",
        commits: "Historique des Commits : Visualise l'arbre Git, cliquez sur les commits pour voir les tâches et les détails.",
        history: "Historique : Enregistre les opérations système et l'historique IA, supporte le retour en arrière."
    }
  },
  settings: {
    title: "Paramètres Système",
    subtitle: "Console Centrale /// PREFERENCES_V2",
    general: {
        title: "Général",
        language: "Langue de l'interface",
        languageDesc: "Sélectionnez la langue principale.",
        profile: "Profil Utilisateur",
        profileDesc: "Géré par le profil de l'espace de travail.",
        adminAccess: "Accès Admin",
        workspace: "Espace de Travail",
        workspaceDesc: "Synchronise les tâches avec le fichier .taskrails local.",
        pickFolder: "Choisir un dossier",
        workspaceLinked: "Projet lié",
        notLinked: "Non lié"
    },
    protocols: {
        title: "Protocoles de Liaison",
        broadcast: "Diffusion d'ID",
        broadcastDesc: "Diffusion auto des changements via MCP aux agents connectés.",
        airlock: "Réinitialisation (Airlock)",
        airlockDesc: "Effacer l'historique de l'IDE lors des changements de contexte.",
        comingSoon: "Bientôt disponible"
    },
    ai: {
        title: "Fournisseur d'IA",
        provider: "Fournisseur",
        apiKey: "Clé API",
        model: "Modèle",
        endpoint: "Endpoint Perso (Optionnel)",
        saveSuccess: "Paramètres IA sauvegardés",
        saveError: "Échec de sauvegarde",
        delete: "Supprimer",
        storedKeys: "Clés stockées",
        noKeys: "Aucune clé stockée",
        providers: {
            openrouter: "OpenRouter (Recommandé)",
            openai: "OpenAI",
            anthropic: "Anthropic",
            google: "Google Gemini",
            xai: "xAI Grok",
            together: "Together AI",
            huggingface: "Hugging Face",
            deepseek: "DeepSeek",
            ollama: "Ollama (Local)",
            custom: "Personnalisé"
        }
    }
  },
  airlock: {
    title: "Contrôle Airlock // Protocole de Revue",
    status: {
        pending: "En attente",
        usage: "USAGE TOKEN",
        risk: "RISQUE"
    },
    risks: {
        low: "Bas",
        medium: "Moyen",
        high: "Élevé"
    },
    actions: {
        reject: "Rejeter",
        approve: "Approuver"
    }
  },
  instruction: {
    title: "Protocoles",
    subtitle: "Manuel Opérationnel",
    banner: "Bienvenue au Centre de Contrôle TaskRails. Ce guide vous aidera à booster votre flux de développement avec l'Architecte IA et le Kanban.",
    modules: {
      objectives: {
        title: "Objectifs de Mission",
        desc: "Le cerveau de votre projet. Chattez avec l'IA pour générer des plans de dév. Les plans peuvent être déployés en un clic sur le Kanban."
      },
      board: {
        title: "Tableau de Mission",
        desc: "Gestion dynamique des tâches. Drag-and-drop, phases et priorités. Les tâches IA sont classées automatiquement."
      },
      role: {
        title: "Contrôle des Rôles",
        desc: "Configurez les agents IA. Paramétrez des prompts uniques pour chaque type d'agent afin de changer leur logique."
      }
    },
    workflow: {
      title: "Flux Standard",
      step1: { title: "Planification", desc: "Allez dans Objectifs de Mission pour commencer à discuter avec l'IA." },
      step2: { title: "Génération Spec", desc: "Après consensus, appliquez la spec IA pour remplir les champs automatiquement." },
      step3: { title: "Déploiement", desc: "Cliquez sur 'DEPLOY TO MISSION BOARD' pour transformer la liste en cartes Kanban." },
      step4: { title: "Exécution", desc: "Gérez les statuts dans le Kanban et suivez les changements dans l'Historique." }
    },
    advanced: {
      title: "Tactiques Avancées",
      mcp: { title: "Support MCP", desc: "Le Model Context Protocol permet aux agents IA d'accéder directement à l'état du Kanban." },
      lang: { title: "Multilingue", desc: "Support complet pour les contextes de développement en plusieurs langues." },
      ui: { title: "Cyberpunk UI", desc: "Interface React 19 + Framer Motion ultra-réactive pour réduire la fatigue visuelle." },
      tip: "Rappel : une bonne planification IA facilite le succès. Vérifiez les titres ## Phase avant de déployer."
    }
  },
  aiPrompts: {
    projectAnalyzer: {
      placeholders: {
        name: "[Get actual name from '## Project Name' above]",
        overview: "[Write 200+ word overview based on scan results]",
        techStack: "[List all detected technologies: Framework | Language | DB | Tools]",
        dataStructure: "[Extract actual interface/model definitions from code]",
        features: "[Analyze code structure, list each module's features]",
        design: "[Observe CSS/style files, describe visual style]",
        rules: "[Detect eslint/prettier configs, describe coding conventions]",
        agentName: "[Name based on tech stack: React Expert, Python Engineer, etc.]",
        agentRole: "[Define role based on project needs]",
        agentPrompt: "[Write 100+ word AI instructions based on project's tech stack and architecture]",
        diagramName: "[Describe what this diagram shows]",
        diagramCode: "[Generate Mermaid diagram based on actual project architecture]"
      },
      langInstruction: "Toutes les valeurs JSON doivent être en français",
      terminologyWarning: "",
      spec: {
        name: "[Use the actual project name from '## Project Name' section above]",
        overview: "Comprehensive project overview (200+ words)",
        techStack: "Framework | Language | Database | Tools",
        dataStructure: "DATA_ARCH: Key data models, schemas, interfaces found.",
        features: "FUNCTIONAL_REQUIREMENTS:\\n## Module Name\\n- Feature 1\\n- Feature 2",
        design: "DESIGN_GUIDELINES: Visual style observations - color schemes, components.",
        rules: "ENGINEERING_PROTOCOLS: Coding conventions - linting, testing, commits."
      },
      agent: {
        leadArchitect: "Architecte Principal",
        systemArchitect: "Architecte Système",
        systemPromptInstruction: "[Generate based on detected tech stack, 100+ words.]"
      },
      diagram: {
        systemArchitecture: "Architecture Système"
      },
      fieldMapping: {
        dataStructure: "Modèles, Schémas, JSON, interfaces",
        design: "Style visuel, branding, couleurs",
        features: "Liste de fonctionnalités en Markdown",
        rules: "Linting, Tests, Commits"
      },
      terminology: {
        code: "code",
        project: "projet",
        variable: "variable",
        database: "base de données",
        deploy: "déployer",
        interface: "interface"
      }
    }
  }
};
