import { TranslationType } from "./zh-TW";

export const ja_JP: TranslationType = {
  common: {
    appName: "TaskRails",
    version: "v2.0",
    importMd: "MDインポート",
    exportMd: "MDエクスポート",
    deleteAll: "すべて削除",
    deleteAllConfirm: "すべてのタスクを削除してもよろしいですか？この操作は取り消せません。",
    deleteConfirm: "このタスクを削除してもよろしいですか？",
    importConfirm: "{count}個のタスクが見つかりました。現在のリストを置き換えますか？",
    noTasksFound: "有効なタスクが見つかりませんでした。フォーマットを確認してください。",
    parseError: "Markdownの解析に失敗しました。",
    yes: "はい",
    no: "いいえ"
  },
  mdExport: {
    header: "TaskRails Project Context",
    autoGenerated: "このファイルはTaskRailsによって自動生成されました。",
    roleRegistry: "ROLE REGISTRY",
    missionBoard: "MISSION BOARD",
    status: {
      todo: "TODO",
      doing: "進行中",
      done: "完了"
    }
  },
  mdImport: {
    statusMap: {
      todo: "TODO",
      doing: "進行中",
      done: "完了"
    }
  },
  projectConfig: {
    items: {
      projectName: "プロジェクト名",
      projectGoal: "プロジェクト目標",
      techStack: "技術スタック",
      features: "機能リスト",
      dataStructure: "データ構造",
      designSpec: "デザイン仕様",
      engineeringRules: "エンジニアリングルール",
      team: "チーム（PM + アーキテクト）",
      diagrams: "ワークフロー（4つの図）"
    },
    status: {
      defined: "定義済み",
      notSet: "未設定",
      notGathered: "未召集",
      notGenerated: "未生成",
      featuresCount: "{count}個の機能",
      expertsCount: "{count}人のエキスパート",
      diagramsCount: "{count}個の図",
      missing: "不足"
    },
    roles: {
      pm: "PM",
      architect: "アーキテクト",
      expert: "エキスパート",
      newMember: "新メンバー"
    },
    diagrams: {
      architecture: "アーキテクチャ図",
      pert: "PERT図",
      sequence: "シーケンス図",
      gantt: "ガントチャート"
    },
    promptPrefix: "あなたは"
  },
  app: {
    kanbanTitle: "カンバンボード",
    kanbanSubtitle: "プロジェクトタスク管理と進捗追跡",
    toast: {
      allTasksDeleted: "すべてのタスクが削除されました",
      deleteFailed: "削除に失敗しました",
      aiAnalyzing: "AIが仕様書を分析し、エージェントを召喚しています...",
      aiInjectSuccess: "{rolesCount}人のエージェントを召喚し、{tasksCount}個のタスクを生成しました",
      aiInjectFailed: "AIタスク注入に失敗しました"
    }
  },
  sidebar: {
    all: "全ミッション",
    main: "メイン機能",
    roleSettings: "ロール設定",
    kanban: "カンバンボード",
    missions: "ミッションリスト",
    engineering: "エンジニアリング",
    issues: "課題管理",
    commits: "コミット履歴",
    history: "操作履歴",
    specs: "設計仕様書",
    manual: "マニュアル",
    admin: "管理者",
    system_op: "システム操作"
  },
  projectAnalyzerUI: {
    title: "プロジェクトアナライザー",
    subtitle: "ソースコードスキャン → AI分析 → 仕様書自動生成",
    loading: {
      scanning: "プロジェクト構造をスキャン中",
      scanningFiles: "ファイルと技術スタックを分析中...",
      aiAnalyzing: "AI分析中",
      lmStudio: "LM Studioで生成中...",
      ollama: "Ollamaで生成中...",
      cloud: "クラウドAIで生成中..."
    },
    aiSource: { lmStudio: "LM Studio", ollama: "Ollama", cloud: "クラウドAI" },
    buttons: {
      projectScan: "プロジェクトスキャン", scanning: "スキャン中...", startScan: "スキャン開始",
      aiGenerate: "AI仕様書生成", generating: "生成中...", generate: "AI生成",
      saveToMemory: "メモリバンクに保存", saveToSpec: "仕様書に保存",
      distributeAgents: "エージェント配布", distributeDiagrams: "ダイアグラム配布", distributeAll: "全て配布"
    },
    labels: { fileCount: "ファイル数", linesOfCode: "コード行数", techStack: "技術スタック", entryPoint: "エントリーポイント", keyFiles: "キーファイル (上位10)" },
    placeholders: { clickScan: "「スキャン開始」をクリックしてプロジェクト構造を分析", scanFirst: "まずプロジェクトをスキャンし、次に「AI生成」をクリック", aiWillGenerate: "AIがスキャン結果に基づいて仕様書を自動生成します" },
    alerts: {
      savedToMemory: "メモリバンク @specs.md に保存しました",
      savedToSpec: "✅ 仕様書に保存しました",
      noAgents: "⚠️ AIエージェントが生成されていません。先に「AI生成」を実行してください",
      agentsDistributed: "✅ {count}個のAIエージェントをチーム設定に配布しました",
      noDiagrams: "⚠️ ダイアグラムが生成されていません。先に「AI生成」を実行してください",
      diagramsDistributed: "✅ {count}個のダイアグラムをワークフロービジュアライザーに配布しました",
      notAnalyzed: "⚠️ AI分析が完了していません。先に「AI生成」を実行してください",
      allDistributed: "🎉 全てのアイテムを配布しました！"
    }
  },
  specs: {
    title: "プロジェクト設計仕様書",
    subtitle: "// プロジェクト仕様・要件定義センター //",
    generateAi: "AIで仕様を生成",
    injectTasks: "カンバンにデプロイ",
    selectCategory: "プロジェクトカテゴリを選択",
    categories: {
        web: "Webアプリケーション",
        desktop: "デスクトップソフト",
        esp: "ハードウェア/ファームウェア (ESP32)",
        backend: "バックエンド/API",
        mobile: "モバイルアプリ",
        game: "ゲーム開発",
        web3: "ブロックチェーン/Web3",
        bot: "ボット/自動化",
        ml: "機械学習/AIデータ",
        extension: "ブラウザ拡張機能"
    },
    aiChat: {
        title: "仕様策定AIコンサルタント",
        placeholder: "開発したいソフトウェアの種類や機能を説明してください...",
        startConsulting: "技術コンサルティング開始",
        stopConsulting: "コンサルティング停止",
        applySpec: "合意事項を仕様書に反映",
        aiThinking: "AIが構築中...",
        welcome: "こんにちは！私はあなたのテクニカルアーキテクトです。何を開発したいか教えていただければ、質問を通じて仕様書の完成をお手伝いします。",
        copy: "コピー",
        stop: "停止",
        systemPrompt: "システムプロンプト",
        savePrompt: "プロンプトを保存",
        copySuccess: "クリップボードにコピーしました",
        defaultSystemPrompt: `あなたはシニアシステムアーキテクト兼テクニカルリードです。あなたのタスクは、ユーザーがゼロから完全な「プロジェクト技術仕様書」を作成するのを支援することです。
1. 深いガイダンス：アーキテクチャ階層、技術スタックの選定、データベーススキーマ、および詳細な機能開発フェーズ（Phases）についてユーザーに考えさせます。
2. 言語基準：常に「日本語」を使用してコミュニケーションを行ってください。
3. 出力基準：計画が成熟したら、積極的に提案するか、以下のJSON形式で直接出力してください：
   \`\`\`json
   { 
     "name": "プロジェクト名", 
     "overview": "ビジョンと概要", 
     "techStack": "詳細な技術スタックリスト", 
     "dataStructure": "データ構造の定義", 
     "features": "## Phase 1...\\n## Phase 2...", 
     "design": "デザイン美学とUI基準", 
     "rules": "エンジニアリング原則と基準" 
   }
   \`\`\``
    },
    placeholders: {
        name: "プロジェクト名",
        overview: "プロジェクトの概要と目標...",
        techStack: "技術スタック (Frontend, Backend, DB...)",
        dataStructure: "データ構造の定義...",
        features: "主要機能リスト (フェーズ1/2順)...",
        design: "デザイン仕様 (色、レイアウト...)",
        rules: "プロジェクトドキュメントのルール..."
    },
    toast: {
        generated: "AI仕様が生成されました",
        injected: "{count}個のタスクをカンバンにインポートしました",
        apiKeyRequired: "先に設定でAI APIキーを設定してください"
    }
  },
  roleSettings: {
    title: "タスクロール設定",
    subtitle: "AIエージェントと共同作業者のロール管理",
    defaultRoles: "デフォルトロール",
    customRoles: "カスタムロール",
    addRole: "ロールを追加",
    roleName: "ロール名",
    agentName: "エージェント名",
    roleType: "タイプ",
    typeAI: "AIエージェント",
    typeHuman: "共同作業者",
    save: "保存",
    delete: "削除",
    noCustomRoles: "カスタムロールはまだありません",
    default: "デフォルト",
    placeholders: { roleName: "例：テストエンジニア", agentName: "例：TestBot-1", systemPrompt: "例：テストエンジニアとして..." },
    systemPromptLabel: "システムプロンプト",
    systemPromptDesc: "MCP経由でAI IDEに送信",
    aiSuggest: "AI提案",
    buttons: { addToQueue: "キューに追加", dispatchToIde: "AI IDEにタスク送信" },
    alerts: { dispatched: "{agentName}のタスクをAI IDEに送信しました！", dispatchFailed: "送信失敗: {error}", noTasks: "追加するタスクがありません", addedToQueue: "{count}個のタスクをキューに追加" },
    defaultAgents: { architect: { name: "アーキテクト", prompt: "システムアーキテクト" }, developer: { name: "開発者", prompt: "シニア開発者" }, reviewer: { name: "レビュアー", prompt: "コードレビュー専門家" } },
    stats: { goals: "目標", tasks: "タスク" }
  },
  roles: {
    coder: "開発者",
    reviewer: "レビュアー",
    architect: "アーキテクト",
    all: "全員"
  },
  tags: {
    general: "一般",
    feature: "機能",
    bug: "バグ",
    enhancement: "改善",
    documentation: "ドキュメント",
    design: "デザイン"
  },
  kanban: {
    title: "プロジェクトダッシュボード",
    subtitle: "// システムステータス: 正常 //",
    searchPlaceholder: "タスクを検索...",
    newTask: "新規タスク",
    columns: {
        todo: "未着手",
        doing: "進行中",
        done: "完了"
    },
    taskModal: {
        titlePlaceholder: "タスク名...",
        descPlaceholder: "Markdownで説明を記述...",
        phase: "フェーズ",
        priority: "優先度",
        tag: "タグ",
        created: "作成日",
        assignee: "担当者",
        unassigned: "未割り当て",
        delete: "削除",
        cancel: "キャンセル",
        save: "変更を保存",
        rework: "リワーク",
        reworkDesc: "内容を未着手に戻す",
        completed: "完了済み",
        reworked: "リワーク済み",
        enterNumber: "数値を入力",
        sortOrder: "ソート順 (低=高優先)"
    }
  },
  missions: {
    title: "ミッションリスト",
    subtitle: "// タスク全件概要 //",
    stats: {
      todo: "未着手",
      doing: "進行中",
      done: "完了",
      reworked: "リワーク済み"
    },
    search: "ID、タイトル、説明で検索...",
    taskCount: "件のタスク",
    noTasks: "タスクはまだありません",
    noMatch: "一致するタスクが見つかりません"
  },
  engineering: {
    title: "エンジニアリングエリア",
    ideControl: "AI IDE コマンドコントロールセンター",
    debug: "デバッグ実行",
    build: "ビルド実行",
    runApp: "アプリ実行",
    commandSent: "AI IDEにコマンドを送信しました:",
    noIssues: "現在、BUGとしてマークされたタスクはありません。",
    noHistory: "操作履歴はまだありません",
    commitsDeveloping: "Gitコミット履歴の統合は開発中です...",
    proposal: {
        issues: "課題トラッキング: タスクシステムとバグ報告を統合し、コード変更をIssue IDと自動リンクします。",
        commits: "コミット履歴: Gitツリーを視覚化し、コミットをクリックして関連タスクとコードの詳細はを確認できます。",
        history: "操作履歴: システムのコア操作とAIの変更履歴を記録し、バージョンのロールバックと監査をサポートします。"
    }
  },
  settings: {
    title: "システム設定",
    subtitle: "コアコンソール /// PREFERENCES_V2",
    general: {
        title: "一般",
        language: "インターフェース言語",
        languageDesc: "システムの主要な表示言語を選択します。",
        profile: "ユーザープロファイル",
        profileDesc: "現在のワークスペース設定で管理されます。",
        adminAccess: "管理者アクセス",
        workspace: "プロジェクトワークスペース",
        workspaceDesc: "ローカルプロジェクトディレクトリ内の .taskrails ファイルにタスクを同期します。",
        pickFolder: "フォルダを選択",
        workspaceLinked: "プロジェクト連携済み",
        notLinked: "未連携"
    },
    protocols: {
        title: "リンクプロトコル",
        broadcast: "IDブロードキャスト",
        broadcastDesc: "MCP経由で接続されたエージェントにロールの変更を自動通知します。",
        airlock: "ハードリセット (エアロック)",
        airlockDesc: "コンテキスト切り替え時にIDEの履歴を強制的にクリアします。",
        comingSoon: "近日公開"
    },
    ai: {
        title: "AIサービスプロバイダー",
        provider: "プロバイダー",
        apiKey: "APIキー",
        model: "モデル",
        endpoint: "カスタムエンドポイント (任意)",
        saveSuccess: "AI設定を保存しました",
        saveError: "AI設定の保存に失敗しました",
        delete: "キーを削除",
        storedKeys: "保存済みキー",
        noKeys: "キーはまだ保存されていません",
        providers: {
            openrouter: "OpenRouter (推奨)",
            openai: "OpenAI",
            anthropic: "Anthropic",
            google: "Google Gemini",
            xai: "xAI Grok",
            together: "Together AI",
            huggingface: "Hugging Face",
            deepseek: "DeepSeek",
            ollama: "Ollama (ローカル)",
            custom: "カスタム (OpenAI互換)"
        }
    }
  },
  airlock: {
    title: "エアロックコントロール // コードレビュープロトコル",
    status: {
        pending: "承認待ち",
        usage: "トークン使用量",
        risk: "リスク"
    },
    risks: {
        low: "低",
        medium: "中",
        high: "高"
    },
    actions: {
        reject: "拒否",
        approve: "変更を承認"
    }
  },
  instruction: {
    title: "使用プロトコル",
    subtitle: "オペレーショナルマニュアル",
    banner: "TaskRailsコマンドセンターへようこそ。このガイドでは、AIアーキテクトとカンバンシステムを活用して開発ワークフローを究極に向上させる方法を説明します。",
    modules: {
      objectives: {
        title: "Mission Objectives",
        desc: "プロジェクトのコアブレインです。AIアーキテクトと対話して、フルスタックの技術開発計画を生成します。計画はワンクリックでカンバンに「デプロイ」できます。"
      },
      board: {
        title: "Mission Board",
        desc: "動的なタスク管理システムです。ドラッグ＆ドロップ、フェーズソート、優先度タグをサポートしています。AI生成タスクは自動的にフェーズに分類されます。"
      },
      role: {
        title: "Role Control",
        desc: "異なるAIエージェントを設定します。開発者、レビュアー、アーキテクトごとに独自のシステムプロンプトを設定し、AIの思考モードを切り替えます。"
      }
    },
    workflow: {
      title: "標準ワークフロー",
      step1: { title: "計画開始", desc: "Mission Objectivesページに移動し、AIコンサルトを使用してAIとの対話を開始します。" },
      step2: { title: "仕様生成", desc: "合意後、「AI仕様を適用」をクリックすると、すべての項目が自動的に入力されます。" },
      step3: { title: "タスク展開", desc: "「DEPLOY TO MISSION BOARD」をクリックして、Markdownリストをカンバンカードに変換します。" },
      step4: { title: "開発実行", desc: "カンバンでタスクステータスを管理し、Engineering Historyですべての変更を追跡します。" }
    },
    advanced: {
      title: "高度な戦術",
      mcp: { title: "MCPサポート", desc: "Model Context Protocolのサポートにより、AIエージェントがカンバンの状態やDBの内容に直接アクセスできるようになります。" },
      lang: { title: "多言語サポート", desc: "多言語の開発コンテキストをフルサポートし、AIとのシームレスなコミュニケーションを保証します。" },
      ui: { title: "Cyberpunk UI", desc: "高速レスポンスのReact 19 + Framer Motionインターフェースが視覚的な疲労を軽減します。" },
      tip: "「優れたAI計画は成功の半分です。タスクをデプロイする前に、## Phaseヘッダーが正しく設定されているか確認してください。これがカンバンのセクションを決定します。」"
    }
  },
  aiPrompts: {
    projectAnalyzer: {
      placeholders: {
        name: "[上記の '## Project Name' から実際の名前を取得]",
        overview: "[スキャン結果に基づいて 200 文字以上の概要を記述]",
        techStack: "[検出されたすべての技術をリスト: フレームワーク | 言語 | DB | ツール]",
        dataStructure: "[コードから実際のインターフェース/モデル定義を抽出]",
        features: "[コード構造を分析し、各モジュールの機能をリスト]",
        design: "[CSS/スタイルファイルを観察し、視覚的スタイルを説明]",
        rules: "[eslint/prettier 設定を検出し、コーディング規約を説明]",
        agentName: "[技術スタックに基づいて命名: React エキスパート、Python エンジニアなど]",
        agentRole: "[プロジェクトのニーズに基づいて役割を定義]",
        agentPrompt: "[プロジェクトの技術スタックとアーキテクチャに基づいて、100 文字以上の AI 指示を作成]",
        diagramName: "[この図が示す内容を説明]",
        diagramCode: "[プロジェクトの実際のアーキテクチャに基づいて Mermaid 図を生成]"
      },
      langInstruction: "すべての JSON 値は日本語で記述してください",
      terminologyWarning: "丁寧な日本語（です・ます調）を使用してください",
      spec: {
        name: "[上記の '## Project Name' セクションの実際のプロジェクト名を使用]",
        overview: "プロジェクトの完全な概要を記述してください（200文字以上）",
        techStack: "技術スタックの詳細。形式：フレームワーク | 言語 | データベース | ツール",
        dataStructure: "DATA_ARCH: コードベースで見つかった主要なデータモデル、スキーマ、インターフェース。",
        features: "FUNCTIONAL_REQUIREMENTS:\\n## モジュール名\\n- 機能 1\\n- 機能 2",
        design: "DESIGN_GUIDELINES: 視覚スタイルの観察 - 配色、コンポーネントパターン、レイアウト。",
        rules: "ENGINEERING_PROTOCOLS: 検出されたコーディング規約 - リンティング、テスト、コミット規約。"
      },
      agent: {
        leadArchitect: "リードアーキテクト",
        systemArchitect: "システムアーキテクト",
        systemPromptInstruction: "[検出された技術スタックに基づいて動的に生成（100文字以上）]"
      },
      diagram: {
        systemArchitecture: "システムアーキテクチャ"
      },
      fieldMapping: {
        dataStructure: "モデル、スキーマ、JSON、インターフェース",
        design: "視覚的スタイル、ブランディング、色",
        features: "Markdownの機能リスト",
        rules: "リンティング、テスト、コミット"
      },
      terminology: {
        code: "コード",
        project: "プロジェクト",
        variable: "変数",
        database: "データベース",
        deploy: "デプロイ",
        interface: "インターフェース"
      }
    }
  }
};
