export type TranslationType = typeof zh_TW;

export const zh_TW = {
  common: {
    appName: "TaskRails",
    version: "v2.0",
    importMd: "匯入 MD",
    exportMd: "匯出 MD",
    deleteAll: "刪除全部",
    deleteAllConfirm: "確定要刪除所有任務嗎？此操作無法恢復。",
    deleteConfirm: "確定要刪除此任務嗎？",
    importConfirm: "探索到 {count} 個任務。是否要取代目前的清單？",
    noTasksFound: "檔案中未發現有效任務，請檢查格式。",
    parseError: "Markdown 解析失敗",
    yes: "是",
    no: "否"
  },
  // MD Export translations
  mdExport: {
    header: "TaskRails Project Context",
    autoGenerated: "此檔案由 TaskRails 自動生成，用於工作區同步與 AI 上下文讀取。",
    roleRegistry: "ROLE REGISTRY",
    missionBoard: "MISSION BOARD",
    status: {
      todo: "待辦事項 / TODO",
      doing: "進行中 / IN PROGRESS",
      done: "已完成 / COMPLETED"
    }
  },
  // MD Import translations (for status mapping)
  mdImport: {
    statusMap: {
      todo: "待辦事項",
      doing: "進行中",
      done: "已完成"
    }
  },
  // Project Config translations
  projectConfig: {
    items: {
      projectName: "專案名稱",
      projectGoal: "專案目標",
      techStack: "技術棧",
      features: "功能清單",
      dataStructure: "資料結構",
      designSpec: "設計規範",
      engineeringRules: "工程規則",
      team: "召集團隊 (PM + 架構師)",
      diagrams: "工作流 (4 張圖表)"
    },
    status: {
      defined: "已定義",
      notSet: "未設定",
      notGathered: "未召集",
      notGenerated: "未生成",
      featuresCount: "{count} 項功能",
      expertsCount: "{count} 位專家",
      diagramsCount: "{count} 張圖表",
      missing: "缺少"
    },
    roles: {
      pm: "PM",
      architect: "架構師",
      expert: "專家顧問",
      newMember: "新成員"
    },
    diagrams: {
      architecture: "架構圖",
      pert: "PERT",
      sequence: "序列圖",
      gantt: "甘特圖"
    },
    promptPrefix: "你是"
  },
  // App.tsx translations
  app: {
    kanbanTitle: "任務看板",
    kanbanSubtitle: "專案任務管理與進度追蹤",
    toast: {
      allTasksDeleted: "所有任務已刪除",
      deleteFailed: "刪除失敗",
      aiAnalyzing: "AI 正在分析說明書並召喚專員與拆解任務...",
      aiInjectSuccess: "成功召喚 {rolesCount} 位專員並生成 {tasksCount} 個詳細任務",
      aiInjectFailed: "AI 任務注入失敗"
    }
  },
  sidebar: {
    all: "全部任務",
    main: "主要功能",
    roleSettings: "角色設定",
    kanban: "任務看板",
    missions: "任務清單",
    engineering: "工程區域",
    issues: "問題追踪",
    commits: "提交記錄",
    history: "歷史記錄",
    specs: "專案說明書",
    manual: "使用手冊",
    admin: "管理員",
    system_op: "系統操作者"
  },
  // ProjectAnalyzer.tsx translations
  projectAnalyzerUI: {
    title: "專案分析器",
    subtitle: "掃描源代碼 → AI 分析 → 自動生成說明書",
    loading: {
      scanning: "掃描專案結構",
      scanningFiles: "正在分析檔案與技術棧...",
      aiAnalyzing: "AI 分析中",
      lmStudio: "使用 LM Studio 生成...",
      ollama: "使用 Ollama 生成...",
      cloud: "使用雲端 AI 生成..."
    },
    aiSource: {
      lmStudio: "LM Studio",
      ollama: "Ollama",
      cloud: "雲端 AI"
    },
    buttons: {
      projectScan: "專案掃描",
      scanning: "掃描中...",
      startScan: "開始掃描",
      aiGenerate: "AI 生成說明書",
      generating: "生成中...",
      generate: "AI 生成",
      saveToMemory: "存至記憶庫",
      saveToSpec: "存至說明書",
      distributeAgents: "分發 Agents",
      distributeDiagrams: "分發流程圖",
      distributeAll: "一鍵全部分發"
    },
    labels: {
      fileCount: "檔案數",
      linesOfCode: "程式碼行數",
      techStack: "技術棧",
      entryPoint: "入口點",
      keyFiles: "關鍵檔案 (前10)"
    },
    placeholders: {
      clickScan: "點擊「開始掃描」分析專案結構",
      scanFirst: "先掃描專案，再點擊「AI 生成」",
      aiWillGenerate: "AI 會根據掃描結果自動生成專案說明書"
    },
    alerts: {
      savedToMemory: "已儲存至記憶庫 @specs.md",
      savedToSpec: "✅ 已儲存至專案說明書",
      noAgents: "⚠️ 尚未生成 AI Agents，請先執行「AI 生成」",
      agentsDistributed: "✅ 已分發 {count} 個 AI Agents 至團隊設定",
      noDiagrams: "⚠️ 尚未生成流程圖，請先執行「AI 生成」",
      diagramsDistributed: "✅ 已分發 {count} 個流程圖至 Workflow Visualizer",
      notAnalyzed: "⚠️ 尚未完成 AI 分析，請先執行「AI 生成」",
      allDistributed: "🎉 已完成全部分發！"
    }
  },
  specs: {
    title: "專案設計說明書",
    subtitle: "// 專案規格與需求定義中心 //",
    generateAi: "AI 智能生成規格",
    injectTasks: "佈署至任務看板",
    selectCategory: "選擇專案類型",
    categories: {
        web: "Web 應用程式",
        desktop: "電腦端軟體",
        esp: "硬體/韌體 (ESP32)",
        backend: "後端系統/API",
        mobile: "行動端 APP",
        game: "遊戲開發 (Game Dev)",
        web3: "區塊鏈/Web3",
        bot: "機器人/自動化 (Bot)",
        ml: "機器學習/AI 數據",
        extension: "瀏覽器擴充外掛"
    },
    aiChat: {
        title: "Spec AI 諮詢專家",
        placeholder: "描述您想開發的軟體類型或功能...",
        startConsulting: "開始技術諮詢",
        stopConsulting: "停止諮詢",
        applySpec: "將共識套用至說明書",
        aiThinking: "AI 正在架構中...",
        welcome: "您好！我是您的技術架構師。請告訴我您想開發什麼，我會透過提問協助您完善規格說明書。",
        copy: "複製",
        stop: "停止生成",
        systemPrompt: "系統指令 (System Prompt)",
        savePrompt: "更新指令",
        copySuccess: "已複製到剪貼簿",
        defaultSystemPrompt: `你是一個資深的系統架構師兼技術組長。你的任務是協助使用者從零開始規劃一套完整的「專案技術說明書」。
1. 深度引導：引導使用者思考架構層級、技術棧選型、資料庫 Schema、以及詳細的功能開發階段（Phases）。
2. 語言規範：必須始終使用「繁體中文（台灣）」進行溝通，術語需符合台灣軟體工程師習慣（如：程式碼、專案、變數、佈署）。
3. 輸出規範：當規劃成熟時，主動建議或直接輸出以下 JSON 格式：
   \`\`\`json
   { 
     "name": "專案名稱", 
     "overview": "願景與概述", 
     "techStack": "技術棧詳細清單", 
     "dataStructure": "資料結構定義", 
     "features": "## Phase 1...\\n## Phase 2...", 
     "design": "設計美學與 UI 規範", 
     "rules": "工程原則與規範" 
   }
   \`\`\``
    },
    placeholders: {
        name: "專案名稱",
        overview: "專案概述與目標...",
        techStack: "技術棧 (Frontend, Backend, DB...)",
        dataStructure: "資料結構定義...",
        features: "核心功能清單 (按 Phase 1/2 排序)...",
        design: "設計規範 (色調, 佈局...)",
        rules: "專案文件規則..."
    },
    toast: {
        generated: "AI 規格已生成",
        injected: "成功匯入 {count} 個任務至看板",
        apiKeyRequired: "請先在設定中配置 AI API Key"
    }
  },
  roleSettings: {
    title: "任務角色設定",
    subtitle: "管理 AI Agent 與協作者角色",
    defaultRoles: "預設角色",
    customRoles: "自訂角色",
    addRole: "新增角色",
    roleName: "角色名稱",
    agentName: "Agent 名稱",
    roleType: "類型",
    typeAI: "AI Agent",
    typeHuman: "協作者",
    save: "儲存",
    delete: "刪除",
    noCustomRoles: "尚未新增自訂角色",
    default: "預設",
    placeholders: {
      roleName: "例：測試工程師",
      agentName: "例：TestBot-1",
      systemPrompt: "例：你是測試工程師，專注於撰寫單元測試與整合測試。確保程式碼覆蓋率達到 80% 以上..."
    },
    systemPromptLabel: "AI 指令 (System Prompt)",
    systemPromptDesc: "透過 MCP 傳送給 AI IDE",
    aiSuggest: "AI Suggest",
    buttons: {
      addToQueue: "添加到任務佇列",
      dispatchToIde: "發送任務給 AI IDE"
    },
    alerts: {
      dispatched: "已派發 {agentName} 的任務到 AI IDE！\n\n指令已複製到剪貼簿，請在 Cursor/VS Code 中貼上執行。",
      dispatchFailed: "派發失敗: {error}",
      noTasks: "此 Agent 沒有任務可添加",
      addedToQueue: "已添加 {count} 個任務到佇列"
    },
    defaultAgents: {
      architect: { name: "架構師", prompt: "你是系統架構師。專注於高層設計、模組劃分、技術選型與架構決策。優先考慮可擴展性、可維護性與效能。" },
      developer: { name: "開發者", prompt: "你是資深開發工程師。專注於撰寫高品質、可測試的程式碼。遵循專案程式碼風格與最佳實踐。" },
      reviewer: { name: "審查者", prompt: "你是程式碼審查專家。專注於發現潛在問題、安全漏洞、效能瓶頸與程式碼品質。提供具體且可執行的改進建議。" }
    },
    stats: {
      goals: "目標",
      tasks: "任務"
    }
  },
  roles: {
    coder: "開發者",
    reviewer: "審查者",
    architect: "架構師",
    all: "全部人員"
  },
  tags: {
    general: "一般",
    feature: "功能",
    bug: "錯誤",
    enhancement: "優化",
    documentation: "文件",
    design: "設計"
  },
  kanban: {
    title: "專案儀表板",
    subtitle: "// 系統狀態：正常 //",
    searchPlaceholder: "搜尋任務...",
    newTask: "新增任務",
    columns: {
        todo: "待辦事項",
        doing: "進行中",
        done: "已完成"
    },
    taskModal: {
        titlePlaceholder: "任務標題...",
        descPlaceholder: "使用 Markdown 撰寫描述...",
        phase: "階段",
        priority: "優先級",
        tag: "標籤",
        created: "建立日期",
        assignee: "負責人",
        unassigned: "未指派",
        delete: "刪除",
        cancel: "取消",
        save: "儲存變更",
        rework: "重工 (Rework)",
        reworkDesc: "將內容複製回待辦事項",
        completed: "已完成",
        reworked: "已重工",
        enterNumber: "輸入數字",
        sortOrder: "排序權重 (低=高優先)"
    }
  },
  missions: {
    title: "任務清單",
    subtitle: "// 全部任務總覽 //",
    stats: {
      todo: "待辦事項",
      doing: "進行中",
      done: "已完成",
      reworked: "已重工"
    },
    search: "搜尋任務 ID、標題或描述...",
    taskCount: "筆任務",
    noTasks: "尚無任務",
    noMatch: "找不到符合的任務"
  },
  engineering: {
    title: "工程區域",
    ideControl: "AI IDE 指令控制中心",
    debug: "執行 DEBUG",
    build: "執行 BUILD",
    runApp: "執行軟體",
    commandSent: "已向 AI IDE 發送指令：",
    noIssues: "目前沒有標示為 BUG 的任務。",
    noHistory: "尚無操作紀錄",
    commitsDeveloping: "Git 提交紀錄整合開發中...",
    proposal: {
        issues: "問題追踪方案：整合任務系統與 Bug 報告，自動連結程式碼變更與 Issue ID。",
        commits: "提交記錄方案：視覺化 Git 樹狀圖，點擊提交可查看對應任務與變更程式碼細節。",
        history: "歷史記錄方案：記錄系統核心操作與 AI 變更歷史，支援程式碼版本回溯與操作審查。"
    }
  },
  settings: {
    title: "系統設定",
    subtitle: "核心控制台 /// PREFERENCES_V2",
    general: {
        title: "一般設定",
        language: "介面語言",
        languageDesc: "選擇系統的主要顯示語言。",
        profile: "使用者配置文件",
        profileDesc: "由目前的工作區配置管理。",
        adminAccess: "管理員權限",
        workspace: "專案工作區",
        workspaceDesc: "將任務同步至本地專案目錄中的 .taskrails 檔案。",
        pickFolder: "選擇資料夾",
        workspaceLinked: "已聯結專案",
        notLinked: "尚未聯結"
    },
    protocols: {
        title: "連結協定",
        broadcast: "身份廣播",
        broadcastDesc: "透過 MCP 自動向已連接的 Agent 廣播角色變更。",
        airlock: "硬重置 (氣閘)",
        airlockDesc: "在切換上下文時強制清除 IDE 歷史記錄。",
        comingSoon: "敬請期待"
    },
    ai: {
        title: "AI 服務提供者",
        provider: "服務商 (Provider)",
        apiKey: "API 金鑰",
        model: "模型 (Model)",
        endpoint: "自定義端點 (Optional)",
        saveSuccess: "AI 設定已儲存",
        saveError: "儲存 AI 設定失敗",
        delete: "刪除金鑰",
        storedKeys: "已存儲的金鑰",
        noKeys: "尚未存儲任何金鑰",
        providers: {
            openrouter: "OpenRouter (推薦)",
            openai: "OpenAI",
            anthropic: "Anthropic",
            google: "Google Gemini",
            xai: "xAI Grok",
            together: "Together AI",
            huggingface: "Hugging Face",
            deepseek: "DeepSeek (深度求索)",
            ollama: "Ollama (本地模型)",
            custom: "自定義 (OpenAI 相容)"
        }
    }
  },
  airlock: {
    title: "氣閘控制 // 代碼審查協定",
    status: {
        pending: "等待批准",
        usage: "TOKEN 使用量",
        risk: "風險"
    },
    risks: {
        low: "低",
        medium: "中",
        high: "高"
    },
    actions: {
        reject: "拒絕",
        approve: "批准變更"
    }
  },
  instruction: {
    title: "使用協定",
    subtitle: "Usage Protocols",
    banner: "歡迎進入 TaskRails 指令中心。本手冊將引導您如何利用 AI 架構師與看板系統，極致提升您的開發工作流。",
    modules: {
      objectives: {
        title: "Mission Objectives",
        desc: "專案的核心大腦。在這裡與 AI 架構師對話，生成完整的技術棧與開發計畫。生成的計畫可一鍵「部署」至任務看板。"
      },
      board: {
        title: "Mission Board",
        desc: "動態任務管理系統。採用拖放式設計，支援階段排序與優先級標註。所有從 AI 生成的任務都會自動歸類到相應階段。"
      },
      role: {
        title: "Role Control",
        desc: "配置不同的 AI 代理人。您可以為開發者、審查者或架構師設定不同的系統指令，切換 AI 的思維模式。"
      }
    },
    workflow: {
      title: "標準工作流",
      step1: { title: "啟動規劃", desc: "進入 Mission Objectives 頁面，使用 AI Consult 與 AI 開始對話。" },
      step2: { title: "生成規格", desc: "當對話完成後，點擊「套用 AI 規格」，系統會自動填入所有開發欄位。" },
      step3: { title: "部署任務", desc: "點擊「DEPLOY TO MISSION BOARD」，將 Markdown 功能清單轉化為看板卡片。" },
      step4: { title: "執行開發", desc: "在看板中管理任務狀態，並透過 Engineering History 追蹤所有更動。" }
    },
    advanced: {
      title: "進階策略",
      mcp: { title: "MCP 整合支援", desc: "支援 Model Context Protocol，讓 AI 代理人能直接存取看板狀態與資料庫內容。" },
      lang: { title: "多語言支援", desc: "完整支援多國語言開發語境，確保與 AI 的溝通無障礙。" },
      ui: { title: "Cyberpunk UI", desc: "極速響應的 React 19 + Framer Motion 動態介面，減少視覺疲勞。" },
      tip: "「記住，好的 AI 規劃是成功的一半。在部署任務前，務必確認功能清單中的 ## Phase 標題是否正確，這將直接決定看板的分段方式。」"
    }
  },
  // AI Prompts translations for getProjectAnalyzerSystemPrompt
  aiPrompts: {
    projectAnalyzer: {
      // Placeholders - instructions for AI to generate dynamic content
      placeholders: {
        name: "[從上方 '## Project Name' 取得實際名稱]",
        overview: "[根據掃描結果撰寫 200 字以上的專案概述]",
        techStack: "[列出偵測到的所有技術，格式：框架 | 語言 | 資料庫 | 工具]",
        dataStructure: "[從程式碼中提取實際的介面/模型定義]",
        features: "[分析程式碼結構，列出各模組功能]",
        design: "[觀察 CSS/樣式檔案，描述視覺風格]",
        rules: "[檢測 eslint/prettier 等配置，描述程式碼規範]",
        agentName: "[根據技術棧命名，如：React 專家、Python 工程師]",
        agentRole: "[根據專案需求定義角色]",
        agentPrompt: "[根據專案技術棧和架構，撰寫 100 字以上的專屬 AI 指令]",
        diagramName: "[描述此圖表展示的內容]",
        diagramCode: "[根據專案實際架構生成 Mermaid 圖]"
      },
      // Language instruction for JSON output
      langInstruction: "所有 JSON 值必須使用繁體中文（台灣用語）",
      // Taiwan-specific terminology warning
      terminologyWarning: "使用台灣在地化術語：程式碼 (NOT 代碼)、專案 (NOT 項目)、變數 (NOT 變量)、資料庫 (NOT 數據庫)、介面 (NOT 接口)",
      // For backward compatibility
      spec: {
        name: "[使用上方 '## Project Name' 區塊提供的實際專案名稱]",
        overview: "請撰寫完整的專案概述，包含：目的、目標用戶、核心價值（200字以上）",
        techStack: "技術棧詳細說明，格式：框架 | 語言 | 資料庫 | 工具",
        dataStructure: "DATA_ARCH: 專案中發現的關鍵資料模型、資料庫結構、JSON 結構、TypeScript 介面。包含欄位類型和關聯。",
        features: "FUNCTIONAL_REQUIREMENTS:\\n## 模組名稱\\n- 功能 1\\n- 功能 2",
        design: "DESIGN_GUIDELINES: 觀察到的視覺風格 - 配色方案、元件樣式、版面配置、品牌元素。",
        rules: "ENGINEERING_PROTOCOLS: 檢測到的程式碼規範 - linting 規則、測試規範、commit 規範、檔案命名、資料夾結構。"
      },
      agent: {
        leadArchitect: "首席架構師",
        systemArchitect: "系統架構師",
        systemPromptInstruction: "[根據偵測到的技術棧動態生成，100字以上。例如：如果是 React + TypeScript 專案，需描述該 Agent 在此技術棧的專業能力、責任範圍、以及如何協助團隊。]"
      },
      diagram: {
        systemArchitecture: "系統架構圖"
      },
      fieldMapping: {
        dataStructure: "模型、結構、JSON、介面",
        design: "視覺風格、品牌、顏色",
        features: "詳細功能列表（Markdown 格式）",
        rules: "Linting、測試、Commit 規範"
      },
      terminology: {
        code: "程式碼",
        project: "專案",
        variable: "變數",
        database: "資料庫",
        deploy: "部署",
        interface: "介面"
      }
    }
  }
};
