// ============ Multi-Platform AI IDE Integration ============
// Generates rule files for various AI IDE platforms

import { AgentRole } from '../components/features/RoleSettingsPage';

// Supported IDE platforms
export type IdePlatform = 
    | 'antigravity'  // Google Antigravity (.antigravity/rules/)
    | 'cursor'       // Cursor (.cursorrules)
    | 'trae'         // ByteDance Trae (.traerules)  
    | 'cline'        // VS Code Cline (.clinerules)
    | 'roocode'      // VS Code Roo Code (.roocodeskills/)
    | 'copilot';     // GitHub Copilot (.github/copilot-instructions.md)

export interface IdeConfig {
    platform: IdePlatform;
    name: string;
    rulesPath: string;
    supportsMultiFile: boolean;
    description: string;
}

// IDE platform configurations
export const IDE_CONFIGS: Record<IdePlatform, IdeConfig> = {
    antigravity: {
        platform: 'antigravity',
        name: 'Google Antigravity',
        rulesPath: '.antigravity/rules/',
        supportsMultiFile: true,
        description: 'Supports multi-file rules and global MCP Store'
    },
    cursor: {
        platform: 'cursor',
        name: 'Cursor',
        rulesPath: '.cursorrules',
        supportsMultiFile: false,
        description: 'Single file rules, use @ to reference directories'
    },
    trae: {
        platform: 'trae',
        name: 'Trae (ByteDance)',
        rulesPath: '.traerules',
        supportsMultiFile: false,
        description: 'Optimized for Chinese instructions and context'
    },
    cline: {
        platform: 'cline',
        name: 'VS Code Cline',
        rulesPath: '.clinerules',
        supportsMultiFile: false,
        description: 'High customization, requires MCP server configuration'
    },
    roocode: {
        platform: 'roocode',
        name: 'VS Code Roo Code',
        rulesPath: '.roocodeskills/',
        supportsMultiFile: true,
        description: 'Skill-based multi-file structure'
    },
    copilot: {
        platform: 'copilot',
        name: 'GitHub Copilot',
        rulesPath: '.github/copilot-instructions.md',
        supportsMultiFile: false,
        description: 'GitHub Copilot custom instructions'
    }
};

// Generate standard Markdown rules for an agent (platform-agnostic)
export function generateAgentRulesMarkdown(agent: AgentRole): string {
    const sections: string[] = [];
    
    // Header
    sections.push(`# Agent: ${agent.agentName}`);
    sections.push(`> Role: ${agent.name}`);
    sections.push(`> Type: ${agent.type === 'ai' ? 'AI Agent' : 'Human Collaborator'}`);
    sections.push('');
    
    // System Prompt / Procedures
    sections.push('## Procedures');
    sections.push('');
    sections.push(agent.systemPrompt || 'No specific procedures defined.');
    sections.push('');
    
    // Skills / Context
    if (agent.skills && agent.skills.length > 0) {
        sections.push('## Context & Skills');
        sections.push('');
        agent.skills.forEach(skill => {
            sections.push(`- ${skill}`);
        });
        sections.push('');
    }
    
    // Goals / Objectives
    if (agent.goals && agent.goals.length > 0) {
        sections.push('## Goals');
        sections.push('');
        agent.goals.forEach((goal, i) => {
            sections.push(`${i + 1}. ${goal}`);
        });
        sections.push('');
    }
    
    // Tasks / Constraints
    if (agent.tasks && agent.tasks.length > 0) {
        sections.push('## Tasks');
        sections.push('');
        agent.tasks.forEach((task, i) => {
            sections.push(`### Task ${i + 1}: ${task.title}`);
            sections.push('');
            sections.push(task.description);
            sections.push('');
        });
    }
    
    // Constraints (standard for all agents)
    sections.push('## Constraints');
    sections.push('');
    sections.push('- Follow project coding conventions');
    sections.push('- Do not modify files outside assigned scope');
    sections.push('- Report progress after each task completion');
    sections.push('- Request clarification when requirements are ambiguous');
    sections.push('');
    
    return sections.join('\n');
}

// Generate platform-specific rules file content
export function generatePlatformRules(
    agents: AgentRole[], 
    platform: IdePlatform,
    projectName: string = 'Project'
): string {
    const config = IDE_CONFIGS[platform];
    const sections: string[] = [];
    
    // Platform-specific header
    switch (platform) {
        case 'antigravity':
            sections.push('# Antigravity Agent Rules');
            sections.push(`# Project: ${projectName}`);
            sections.push('# Auto-generated by TaskRails');
            sections.push('');
            break;
        case 'cursor':
            sections.push('# Cursor Rules');
            sections.push(`# Project: ${projectName}`);
            sections.push('');
            sections.push('## Team Configuration');
            sections.push('');
            sections.push('This project uses a multi-agent team approach.');
            sections.push('Reference specific agent rules with @.taskrails/agents/');
            sections.push('');
            break;
        case 'trae':
            sections.push('# Trae 規則檔案');
            sections.push(`# 專案: ${projectName}`);
            sections.push('');
            break;
        case 'cline':
        case 'roocode':
            sections.push('# VS Code Agent Rules');
            sections.push(`# Project: ${projectName}`);
            sections.push('');
            break;
        case 'copilot':
            sections.push('# GitHub Copilot Instructions');
            sections.push(`# Project: ${projectName}`);
            sections.push('');
            sections.push('## AI Assistant Behavior');
            sections.push('');
            break;
    }
    
    // Add agents
    agents.forEach(agent => {
        sections.push(generateAgentRulesMarkdown(agent));
        sections.push('---');
        sections.push('');
    });
    
    return sections.join('\n');
}

// Generate MCP configuration for shared state
export function generateMcpConfig(projectPath: string): object {
    return {
        version: "1.0",
        project: projectPath,
        servers: {
            sqlite: {
                command: "mcp-server-sqlite",
                args: ["--db-path", "./data/task_status.db"]
            },
            filesystem: {
                command: "mcp-server-filesystem", 
                args: ["./"]
            }
        },
        sharedState: {
            database: "./data/task_status.db",
            tables: ["tasks", "agents", "status_log"]
        },
        teamSync: {
            enabled: true,
            pollInterval: 5000
        }
    };
}

// Get the appropriate file path for a platform's rules
export function getRulesFilePath(platform: IdePlatform, agentId?: string): string {
    const config = IDE_CONFIGS[platform];
    
    if (config.supportsMultiFile && agentId) {
        // For platforms that support multiple files, create agent-specific files
        if (platform === 'antigravity') {
            return `.antigravity/rules/${agentId}.md`;
        } else if (platform === 'roocode') {
            return `.roocodeskills/${agentId}.md`;
        }
    }
    
    return config.rulesPath;
}

// Directory structure for team environment
export const TEAM_DIRECTORY_STRUCTURE = {
    antigravity: '.antigravity/rules/',
    cursor: '.cursorrules',
    trae: '.traerules',
    cline: '.clinerules',
    roocode: '.roocodeskills/',
    copilot: '.github/copilot-instructions.md',
    shared: {
        data: 'data/',
        mcpConfig: 'mcp_config.json',
        taskrails: '.taskrails/'
    }
};
